### ISSUE TITLE
Not compatible with 1.19.3

### ISSUE THREAD

**Issue by Zorklis** [DallenB4/fast-portals#2]
[Info: 2022-12-24 22:15:05.2440948: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/GameProvider (main) Info Loading Minecraft 1.19.3 with Fabric Loader 0.14.11
[Info: 2022-12-24 22:15:05.8910978: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Resolution (main) Warn Mod resolution failed
[Info: 2022-12-24 22:15:05.8916672: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Resolution (main) Info Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED fast-portals 1.0.1 {depends minecraft @ [>=1.16 <=1.19.2]}, ROOT_FORCELOAD_SINGLE fast-portals 1.0.1]
[Info: 2022-12-24 22:15:05.8918864: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Resolution (main) Info Reason: [HARD_DEP fast-portals 1.0.1 {depends minecraft @ [>=1.16 <=1.19.2]}]
[Info: 2022-12-24 22:15:05.8921326: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Resolution (main) Info CLIENT environment disabled: [skinrestorer]
[Info: 2022-12-24 22:15:05.8938995: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Resolution (main) Info Fix: add [], remove [], replace [[fast-portals 1.0.1] -> add:fast-portals 1 ([(-∞,∞)])]
[Info: 2022-12-24 22:15:05.9161032: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader (main) Error Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fast Portals' (fast-portals) 1.0.1 with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'Fast Portals' (fast-portals) 1.0.1 requires any version between 1.16 (inclusive) and 1.19.2 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by DallenB4** [comment]
Fixed.
